# Generated by Django 2.2 on 2020-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
