# Generated by Django 2.2 on 2020-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200727_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='textbook.jpg', upload_to='profile_pics'),
        ),
    ]
